name: kara
description: A KARA implementation in Dart
version: 0.0.0
repository: https://github.com/libkara/dart-kara

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
